### PR TITLE
Fix incorrect import of IComponentLookup for test compatibility with zope.component 5

### PR DESCRIPTION
**Pull request by jamadden**

### CODE REVIEW

**Review by dataflake — COMMENTED** [review]
With the changes to `CHANGES.rst` you now have clashing header levels with `README.rst`. Was that intended? I'd rather leave those cosmetic changes alone unless there's a real rendering issue.

**Comment by jamadden** [comment]
No, README.rst also has the correct header levels.

**Review by dataflake — APPROVED** [review]
Oh, you're right, I overlooked that. 0.5 points off for the "cosmetic changes mixed in with functional changes" party foul, though...

**Comment by jamadden** [comment]
Fair enough, my bad. Straightening the ReST adornments according to the ReST standard script is an automatic part of my workflow and sometimes I forget to stop it…

Thank you.

**Comment by dataflake** [comment]
No worries, I was making fun, mostly. I am wondering where the delineation among the zopefoundation packages is with one side using the simple equal sign underline as top level and the other doing the full surround. I know all the Zope 4/5 packages I deal with have the simple underline as somewhat of an unspoken convention.

**Pull request merged**
